url: http://strangerways.local
name: Stranger Ways
description:
markdown: redcarpet
permalink: pretty

exclude: ['Gemfile', 'Gemfile.lock', 'README.md']
gallery:
  dir: photos

navigation:
  - text: Home
    url: /
  - text: Videos
    url: http://www.youtube.com/user/StrangerWaysMusic
  - text: Music
    url: /music
  - text: Photos
    url: /photos
  - text: Shows
    url: /shows
  - text: The Band
    url: /about